spring:
    application:
        name: indian-ad-api

    jpa:
        hibernate:
            ddl-auto: update
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5433/mydb
        username: root
        password: pass

    data:
       mongodb:
           username: root
           password: pass
           host: localhost
           port: 27020
           database: mydb
           authentication-database: admin

    servlet:
        multipart:
            enabled: true
            max-file-size: 5MB
            max-request-size: 5MB

server:
    port: 8080
    error:
        include-message: always

security:

    jwt:
        secret: ${JWT_SECRET}
        lifetime: 3600000 # 60 min
#        lifetime: 180000 # 3 min

    refresh:
        lifetime: 36000000 # 600 min
#        lifetime: 300000 # 5 min

aws:
    credentials:
        access-key-id: ${S3_ACCESS_KEY}
        access-secret-key: ${S3_SECRET_KEY}

    s3:
        bucket-name: ${S3_BUCKET_NAME}

    region: ru-central1

